In [89]:
print('hello')

hello


In [90]:
?print

In [91]:
%lsmagic

Available line magics:
%alias  %alias_magic  %autoawait  %autocall  %automagic  %autosave  %bookmark  %cat  %cd  %clear  %colors  %conda  %config  %connect_info  %cp  %debug  %dhist  %dirs  %doctest_mode  %ed  %edit  %env  %gui  %hist  %history  %killbgscripts  %ldir  %less  %lf  %lk  %ll  %load  %load_ext  %loadpy  %logoff  %logon  %logstart  %logstate  %logstop  %ls  %lsmagic  %lx  %macro  %magic  %man  %matplotlib  %mkdir  %more  %mv  %notebook  %page  %pastebin  %pdb  %pdef  %pdoc  %pfile  %pinfo  %pinfo2  %pip  %popd  %pprint  %precision  %prun  %psearch  %psource  %pushd  %pwd  %pycat  %pylab  %qtconsole  %quickref  %recall  %rehashx  %reload_ext  %rep  %rerun  %reset  %reset_selective  %rm  %rmdir  %run  %save  %sc  %set_env  %store  %sx  %system  %tb  %time  %timeit  %unalias  %unload_ext  %who  %who_ls  %whos  %xdel  %xmode

Available cell magics:
%%!  %%HTML  %%SVG  %%bash  %%capture  %%debug  %%file  %%html  %%javascript  %%js  %%latex  %%markdown  %%perl  %%prun  %%pypy  %%

In [92]:
# %load 
import numpy as np
print('hello')
?print
%lsmagic

hello


Available line magics:
%alias  %alias_magic  %autoawait  %autocall  %automagic  %autosave  %bookmark  %cat  %cd  %clear  %colors  %conda  %config  %connect_info  %cp  %debug  %dhist  %dirs  %doctest_mode  %ed  %edit  %env  %gui  %hist  %history  %killbgscripts  %ldir  %less  %lf  %lk  %ll  %load  %load_ext  %loadpy  %logoff  %logon  %logstart  %logstate  %logstop  %ls  %lsmagic  %lx  %macro  %magic  %man  %matplotlib  %mkdir  %more  %mv  %notebook  %page  %pastebin  %pdb  %pdef  %pdoc  %pfile  %pinfo  %pinfo2  %pip  %popd  %pprint  %precision  %prun  %psearch  %psource  %pushd  %pwd  %pycat  %pylab  %qtconsole  %quickref  %recall  %rehashx  %reload_ext  %rep  %rerun  %reset  %reset_selective  %rm  %rmdir  %run  %save  %sc  %set_env  %store  %sx  %system  %tb  %time  %timeit  %unalias  %unload_ext  %who  %who_ls  %whos  %xdel  %xmode

Available cell magics:
%%!  %%HTML  %%SVG  %%bash  %%capture  %%debug  %%file  %%html  %%javascript  %%js  %%latex  %%markdown  %%perl  %%prun  %%pypy  %%

# операции с векторами

In [93]:
import numpy as np

In [94]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])

In [95]:
a.shape == b.shape

True

In [96]:
a + b

array([ 7,  9, 11, 13, 15])

сравним вектора со списками

In [97]:
x1 = [1,2,3,4,5]
x2 = [6,7,8,9,10]

In [98]:
x1 + x2

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [99]:
np.add(a, b)

array([ 7,  9, 11, 13, 15])

In [100]:
a - b 

array([-5, -5, -5, -5, -5])

In [101]:
np.subtract(a, b)

array([-5, -5, -5, -5, -5])

### умноежние вектора на скаляр

In [102]:
a * 2

array([ 2,  4,  6,  8, 10])

In [103]:
b * 1.5

array([ 9. , 10.5, 12. , 13.5, 15. ])

сравнение со списком

In [104]:
x1 * 2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [105]:
a.dot(-10)

array([-10, -20, -30, -40, -50])

In [106]:
np.dot(-10, a)

array([-10, -20, -30, -40, -50])

In [107]:
np.multiply(-10, a)

array([-10, -20, -30, -40, -50])

### скалярное произведение векторов

In [108]:
a * b      # просто перемножились каждый с каждым элемент

array([ 6, 14, 24, 36, 50])

In [109]:
sp = a[0] * b[0] + a[1] * b[1] + a[2] * b[2] + a[3] * b[3] + a[4] * b[4]
sp

130

In [110]:
a @ b

130

In [111]:
np.dot(a,b)

130

# операции с матрицами

In [112]:
a = np.array([[0,1],
             [2,3],
             [4,5]])
b = np.array([[6,7],
             [8,9], 
             [10,11]])

In [113]:
a.shape

(3, 2)

In [114]:
a.shape == b.shape

True

In [115]:
a + b

array([[ 6,  8],
       [10, 12],
       [14, 16]])

In [116]:
np.add(a,b)

array([[ 6,  8],
       [10, 12],
       [14, 16]])

In [117]:
#вычитание и умножение аналогично

### умножение матриц

In [118]:
x1 = np.array([[1,2],
               [3,4],
               [5,6]])
x2 = np.array([[6,7,8,9], 
               [10,11,12,13]])
# число столбцов shape[1] 1 матрицы равно числу строк shape[0] 2 матрицы и все!

In [119]:
x1.shape[1] == x2.shape[0]

True

In [120]:
np.dot(x1,x2) # x1[0,0]*x2[0,0] + x1[0,1]*x2[1,0] = 1*6+3*10 = 26

array([[ 26,  29,  32,  35],
       [ 58,  65,  72,  79],
       [ 90, 101, 112, 123]])

модуль np.linalg

In [121]:
x1 = np.array([[1,2],
               [3,4]])

In [122]:
np.dot(x1,x1) #возведение в квадрат только квадратная матрица

array([[ 7, 10],
       [15, 22]])

In [123]:
np.linalg.matrix_power(x1,2) #степень неотр целое

array([[ 7, 10],
       [15, 22]])

## создание единичной матрицы

In [124]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

###  умножение матрицы на ед матрицу

In [125]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [126]:
np.dot(I, a) # столбцы 1 матрицы = строки 2 матрицы

array([[0., 1.],
       [2., 3.],
       [4., 5.]])

In [127]:
I = np.eye(2)
I

array([[1., 0.],
       [0., 1.]])

In [128]:
np.dot(a, I)

array([[0., 1.],
       [2., 3.],
       [4., 5.]])

### транспонирование матрицы

In [129]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [130]:
a.transpose()

array([[0, 2, 4],
       [1, 3, 5]])

In [131]:
a.T

array([[0, 2, 4],
       [1, 3, 5]])

# вычисление определителя и ранга матрицы

для определителя - квадратная матрица

ранг определяет сколько строк линейно независимы

In [132]:
a = np.array([[0,1],
              [2,3]])

In [133]:
np.linalg.det(a)

-2.0

In [134]:
np.linalg.matrix_rank(a)

2

In [135]:
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [136]:
np.linalg.matrix_rank(b)

2

### вычисление обратной матрицы: умножение исходной матрицы на нее дает ед матрицу 

In [137]:
a

array([[0, 1],
       [2, 3]])

In [138]:
np.linalg.inv(a)

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [139]:
np.dot(a, I)

array([[0., 1.],
       [2., 3.]])

# автоматическое создание массивов

In [140]:
a = np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [141]:
b = np.ones((5,3))
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [142]:
c = np.arange(10)
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [143]:
np.arange(2,20,4) # шаг 4

array([ 2,  6, 10, 14, 18])

In [144]:
np.arange(10, 0, -1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [145]:
np.arange(10, 0, -0.5)

array([10. ,  9.5,  9. ,  8.5,  8. ,  7.5,  7. ,  6.5,  6. ,  5.5,  5. ,
        4.5,  4. ,  3.5,  3. ,  2.5,  2. ,  1.5,  1. ,  0.5])

In [146]:
np.linspace(1, 10, 20) #включена и 1, и 10

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [147]:
np.logspace(0,3,4) #обе границы включены, но числа не сами, а степени числа 10

array([   1.,   10.,  100., 1000.])

## генерачия случайных чисел

**np.random.sample()** - случайные числа, равномерное распределение от 0 до 1

In [148]:
np.random.sample()

0.6011150117432088

In [149]:
np.random.sample(3)

array([0.70807258, 0.02058449, 0.96990985])

In [150]:
np.random.sample((2,3))

array([[0.83244264, 0.21233911, 0.18182497],
       [0.18340451, 0.30424224, 0.52475643]])

**np.random.randn()** - случайные числа, нормальное распределение (ср = 0, средн.кв = 1)

In [151]:
np.random.randn(3)

array([-1.72491783, -0.56228753, -1.01283112])

In [152]:
np.random.randn(3,4)

array([[ 0.31424733, -0.90802408, -1.4123037 ,  1.46564877],
       [-0.2257763 ,  0.0675282 , -1.42474819, -0.54438272],
       [ 0.11092259, -1.15099358,  0.37569802, -0.60063869]])

**np.random.randint()** - массив из целых чисел от 0 до 100

In [153]:
np.random.randint(0, 100, 10)

array([83, 91, 59, 70, 43,  7, 46, 34, 77, 80])

In [154]:
np.random.randint(0, 10, (3,4))

array([[3, 1, 7, 3],
       [1, 5, 5, 9],
       [3, 5, 1, 9]])

**np.random.choice()** - случайный выбор элементов из массива

In [155]:
b = np.random.randint(0, 10, 10)
b

array([1, 9, 3, 7, 6, 8, 7, 4, 1, 4])

In [156]:
np.random.choice(b)

4

In [157]:
np.random.choice(b, 3)

array([4, 1, 1])

**np.random.seed()** - инициализация случайных чисел, при установленном seed одни и те же числа

In [158]:
np.random.seed(42)
np.random.randint(0, 10, 10)

array([6, 3, 7, 4, 6, 9, 2, 6, 7, 4])

### изменение формы массива

In [159]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [160]:
a.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

можно указать только кол-во строк или столбцов, а вместо другого -1 

In [161]:
np.reshape(a, (3, -1))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [162]:
np.reshape(a, (-1, 2))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

поменять форму массива

In [163]:
a.resize(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

сделать одномерным массивом

In [164]:
a = a.flatten()

In [165]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

# соединение массивов

In [166]:
a = np.zeros((2,3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [167]:
b = np.ones((2,3))
b

array([[1., 1., 1.],
       [1., 1., 1.]])

соединение массисов вертикально 

In [168]:
v = np.vstack((a,b))
v

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [169]:
a.shape, b.shape, v.shape

((2, 3), (2, 3), (4, 3))

In [170]:
np.concatenate((a,b), axis = 0)

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.]])

соединение массисов горизонтально 

In [171]:
h = np.hstack((a,b))
h

array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])

In [172]:
a.shape, b.shape, h.shape

((2, 3), (2, 3), (2, 6))

In [173]:
np.concatenate((a,b), axis = 1)

array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])

соединение массисов в глубину (в 3 измерении) 

In [174]:
d = np.dstack((a,b))  # а будет ближе, б дальше
d

array([[[0., 1.],
        [0., 1.],
        [0., 1.]],

       [[0., 1.],
        [0., 1.],
        [0., 1.]]])

In [180]:
x2 = np.array([[ 6,  7,  8,  9],
               [10, 11, 12, 13],
               [3, 6, 9, 34]])

сортировка массива по 1 столбцу в порядке возрастания. Как итог строки меняются местами во всем массиве

In [184]:
x2[x2[:, 0].argsort(), :] 

array([[ 3,  6,  9, 34],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

## перемешивание данных в массиве

In [186]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [187]:
np.random.shuffle(a)

In [188]:
a

array([0, 6, 9, 1, 4, 5, 2, 8, 7, 3])

In [190]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [191]:
np.random.shuffle(a) ## перемешиваются только строки, но не стобцы

In [192]:
a

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [ 4,  5,  6,  7]])

# математические действия

In [202]:
a = np.arange(1,7).reshape(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [203]:
np.log(a)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947]])

In [204]:
np.exp(a)

array([[  2.71828183,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [205]:
a.sum() # сумма всех элементов

21

In [206]:
a.sum(axis = 0) # сумма столбов

array([5, 7, 9])

In [207]:
a.sum(axis = 1) #сумма строк

array([ 6, 15])

In [208]:
10 + a

array([[11, 12, 13],
       [14, 15, 16]])

# Broadcasting

если одинаковое кол-во столбов, то сложатся строки с одной строкой столько сколько нужно раз

аналогично со столбцами

# статистические функции

min max mean std для всего массива в целом, а также для строк (axis = 0) и столбцов (axis = 1) отдельно  

In [209]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [211]:
a.min(axis = 1)

array([1, 4])

# запись и чтение

In [212]:
np.save('a.npy', a)

In [213]:
b = np.load('a.npy')
b

array([[1, 2, 3],
       [4, 5, 6]])